name: DeadLib
version: '${version}'

main: dead.deadLib.DeadLib
api-version: '1.21'
load: POSTWORLD

softdepend: ["PlaceholderAPI"]
commands:
  deadlib:
    permission: op
  itemeditor:
    permission: op
  itemstorage:
    permission: op