name: VoidrunnerCore
version: '${version}'

main: dead.voidrunnerCore.VoidrunnerCore
api-version: '1.21.11'
load: POSTWORLD

softdepend: ["PlaceholderAPI"]
commands:
  vrcore:
    permission: op
  itemeditor:
    permission: op
  itemstorage:
    permission: op